### ISSUE TITLE
Can not load wallet from file

### ISSUE THREAD

**Issue by yoSir** [pokkst/bitcoincashj#7]
I tried to use this library to restore a wallet from mnemonic code first in testnet. And then through the `autosaveToFile` method, the wallet was persisted to a file. However, after I restarted my project and tried to load the wallet from the file with the `loadFromFile` method. An exception was thrown out. 
```log
java.lang.IllegalArgumentException: No key found for absolute path M/44H/145H/0H/0/2.
	at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:88) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:656) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:649) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.KeyChainGroup.createCurrentKeysMap(KeyChainGroup.java:1050) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.KeyChainGroup.fromProtobufUnencrypted(KeyChainGroup.java:913) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:512) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:450) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:424) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.Wallet.loadFromFileStream(Wallet.java:1823) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.Wallet.loadFromFileStream(Wallet.java:1819) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.wallet.Wallet.loadFromFile(Wallet.java:1725) ~[bitcoinj-core-0.25.jar:?]
```

**Comment by pokkst** [comment]
Please see WalletKitCore.java for how to correctly save and load a wallet file. 

https://github.com/pokkst/bitcoincashj/blob/master/core/src/main/java/org/bitcoinj/kits/WalletKitCore.java#L382

Thanks.
