### ISSUE TITLE
How to get an Address or CashAddress Object from a String like "bchtest:qp4xajdr98q9qg5j5gqm5lrptty8ha3l5v3v83nzm0"

### ISSUE THREAD

**Issue by yoSir** [pokkst/bitcoincashj#8]
After I get a bch address like `"bchtest:qp4xajdr98q9qg5j5gqm5lrptty8ha3l5v3v83nzm0"` with the method `toCash` of `Address` class. Then How can I get an `Address` or `CashAddress` Object from this address of `String` type? After I use the method `fromBase58` of `Address` or `CashAddress`, an exception was throw out.
```
org.bitcoinj.core.AddressFormatException$InvalidCharacter: Invalid character ':' at position 7
	at org.bitcoinj.core.Base58.decode(Base58.java:133) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.core.Base58.decodeChecked(Base58.java:172) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.core.VersionedChecksummedBytes.<init>(VersionedChecksummedBytes.java:41) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.core.Address.<init>(Address.java:182) ~[bitcoinj-core-0.25.jar:?]
	at org.bitcoinj.core.Address.fromBase58(Address.java:99) ~[bitcoinj-core-0.25.jar:?]
```

**Comment by pokkst** [comment]
AddessFactory.create().getAddress("addressHere");

Please stop opening issues for simple things that can either be found in unit tests or examples.

**Comment by pokkst** [comment]
It should also be noted that
"bchtest:qp4xajdr98q9qg5j5gqm5lrptty8ha3l5v3v83nzm0"
is not in Base58 encoding to begin with. You seem to have a misunderstanding of Bitcoin Cash addresses altogether.
